# Generated by Django 3.2.6 on 2021-08-19 03:34

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="isvoted",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Updated on"
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Email Address",
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="mobile_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, verbose_name="Mobile Number"
            ),
        ),
    ]
