# Generated by Django 3.2.6 on 2021-08-19 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("restaurant", "0002_auto_20210819_0334"),
    ]

    operations = [
        migrations.AlterField(
            model_name="isvoted",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_voted",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User Voted",
            ),
        ),
    ]
