# Generated by Django 3.2.6 on 2021-08-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_alter_menu_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
